name: Further.
favicon: null
layout_spectrum: 0.01462
typography_spectrum: 0.56836
title: Further.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00022b'
    - '#b7a483'
    - '#353c4d'
    - '#5c5b60'
    - '#f3c99f'
  brandStrength: 0.6875
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
