name: Further.
favicon: null
layout_spectrum: 0.48666
typography_spectrum: 0.54605
title: Further.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a99f95'
    - '#1b1a18'
    - '#ccc8bd'
    - '#eeebe4'
    - '#776c6a'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
